version: '3.8'

services:
  db:
    restart: always
    image: postgres:16.3-alpine
    volumes:
    - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5436:${DB_PORT}"

volumes:
  db: