version: '3.8'

services:
  db:
    container_name: "todo_app_go_postgres"
    image: postgres:16.3-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: